


# --- Supabase Configuration ---
[supabase]
SUPABASE_URL = "https://wofgqoyejugnxriciucl.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvZmdxb3llanVnbnhyaWNpdWNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNTkyNTQsImV4cCI6MjA1NzczNTI1NH0.93ivhjGRe_PK6nppsE8XIXjlk7dkMTNNfLIzKVqEP9Y"

# --- OpenRouter AI Setup ---
[openrouter]
OPENROUTER_API_KEY = "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"
